version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-app
    env_file:
      - .env 
    ports:
      - "8000:8000"
    restart: unless-stopped