version: "3.8"

services:
  web:
    image: ghcr.io/suspensenop/django-weather-api-app:latest
    container_name: weather-app
    env_file:
      - .env 
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports: 
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 

